export enum RDErrorCode {
    UNDEFINED,

    SLOT_ALREADY_FILLED,
    UNREGISTERED_SLOT,
    STATE_ALREADY_ACTIVE,

    DICE_INDEX_EMPTY,
    DICE_IF_FULL,
    DICE_INDEX_FULL,
    DICE_NOT_FULL,

    NO_FINAL_SCORE_CELL,
    NO_ANY_CELL,
}
