export enum RDErrorCode {
    UNDEFINED,

    STATE_ID_ALREADY_USED,
    UNREGISTERED_PROTOCOL_ID,

    DICE_INDEX_EMPTY,
    DICE_IF_FULL,
    DICE_INDEX_FULL,
    DICE_NOT_FULL,

    NO_FINAL_SCORE_CELL,
    NO_ANY_CELL,
}
