export const enum RDErrorCode {
    UNDEFINED = "UNDEFINED",

    DICE_INDEX_EMPTY = "DICE_INDEX_EMPTY",
    DICE_IF_FULL = "DICE_IF_FULL",
    DICE_INDEX_FULL = "DICE_INDEX_FULL",
    DICE_NOT_FULL = "DICE_NOT_FULL",

    NO_FINAL_SCORE_CELL = "NO_FINAL_SCORE_CELL",
    NO_ANY_CELL = "NO_ANY_CELL",
}
